/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProxyRouteImport } from './routes/app.proxy'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminSubusersRouteImport } from './routes/app.admin.subusers'
import { Route as AppAdminOrdersRouteImport } from './routes/app.admin.orders'
import { Route as AppAdminConfigRouteImport } from './routes/app.admin.config'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProxyRoute = AppProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSubusersRoute = AppAdminSubusersRouteImport.update({
  id: '/admin/subusers',
  path: '/admin/subusers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrdersRoute = AppAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminConfigRoute = AppAdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/proxy': typeof AppProxyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/config': typeof AppAdminConfigRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/subusers': typeof AppAdminSubusersRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/proxy': typeof AppProxyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/config': typeof AppAdminConfigRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/subusers': typeof AppAdminSubusersRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/proxy': typeof AppProxyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/config': typeof AppAdminConfigRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/subusers': typeof AppAdminSubusersRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/proxy'
    | '/app/settings'
    | '/app/admin/config'
    | '/app/admin/orders'
    | '/app/admin/subusers'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/proxy'
    | '/app/settings'
    | '/app/admin/config'
    | '/app/admin/orders'
    | '/app/admin/subusers'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/proxy'
    | '/app/settings'
    | '/app/admin/config'
    | '/app/admin/orders'
    | '/app/admin/subusers'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proxy': {
      id: '/app/proxy'
      path: '/proxy'
      fullPath: '/app/proxy'
      preLoaderRoute: typeof AppProxyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/subusers': {
      id: '/app/admin/subusers'
      path: '/admin/subusers'
      fullPath: '/app/admin/subusers'
      preLoaderRoute: typeof AppAdminSubusersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/orders': {
      id: '/app/admin/orders'
      path: '/admin/orders'
      fullPath: '/app/admin/orders'
      preLoaderRoute: typeof AppAdminOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/config': {
      id: '/app/admin/config'
      path: '/admin/config'
      fullPath: '/app/admin/config'
      preLoaderRoute: typeof AppAdminConfigRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProxyRoute: typeof AppProxyRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminConfigRoute: typeof AppAdminConfigRoute
  AppAdminOrdersRoute: typeof AppAdminOrdersRoute
  AppAdminSubusersRoute: typeof AppAdminSubusersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProxyRoute: AppProxyRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminConfigRoute: AppAdminConfigRoute,
  AppAdminOrdersRoute: AppAdminOrdersRoute,
  AppAdminSubusersRoute: AppAdminSubusersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
