/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResidentialProxyRouteImport } from './routes/residential-proxy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProxyRouteImport } from './routes/app.proxy'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSubusersRouteImport } from './routes/app.admin.subusers'
import { Route as AppAdminSeoRouteImport } from './routes/app.admin.seo'
import { Route as AppAdminOrdersRouteImport } from './routes/app.admin.orders'
import { Route as AppAdminConfigRouteImport } from './routes/app.admin.config'
import { Route as ApiPublicHooksSyncUsageRouteImport } from './routes/api/public/hooks/sync-usage'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialProxyRoute = ResidentialProxyRouteImport.update({
  id: '/residential-proxy',
  path: '/residential-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProxyRoute = AppProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSubusersRoute = AppAdminSubusersRouteImport.update({
  id: '/admin/subusers',
  path: '/admin/subusers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSeoRoute = AppAdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrdersRoute = AppAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminConfigRoute = AppAdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksSyncUsageRoute = ApiPublicHooksSyncUsageRouteImport.update({
  id: '/api/public/hooks/sync-usage',
  path: '/api/public/hooks/sync-usage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/residential-proxy': typeof ResidentialProxyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/proxy': typeof AppProxyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/config': typeof AppAdminConfigRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/seo': typeof AppAdminSeoRoute
  '/app/admin/subusers': typeof AppAdminSubusersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/api/public/hooks/sync-usage': typeof ApiPublicHooksSyncUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/residential-proxy': typeof ResidentialProxyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/proxy': typeof AppProxyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/config': typeof AppAdminConfigRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/seo': typeof AppAdminSeoRoute
  '/app/admin/subusers': typeof AppAdminSubusersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/api/public/hooks/sync-usage': typeof ApiPublicHooksSyncUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/residential-proxy': typeof ResidentialProxyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/proxy': typeof AppProxyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/config': typeof AppAdminConfigRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/seo': typeof AppAdminSeoRoute
  '/app/admin/subusers': typeof AppAdminSubusersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/api/public/hooks/sync-usage': typeof ApiPublicHooksSyncUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/locations'
    | '/pricing'
    | '/refund-policy'
    | '/residential-proxy'
    | '/sitemap.xml'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/proxy'
    | '/app/settings'
    | '/app/admin/config'
    | '/app/admin/orders'
    | '/app/admin/seo'
    | '/app/admin/subusers'
    | '/app/admin/users'
    | '/app/admin/'
    | '/api/public/hooks/sync-usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/locations'
    | '/pricing'
    | '/refund-policy'
    | '/residential-proxy'
    | '/sitemap.xml'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/proxy'
    | '/app/settings'
    | '/app/admin/config'
    | '/app/admin/orders'
    | '/app/admin/seo'
    | '/app/admin/subusers'
    | '/app/admin/users'
    | '/app/admin'
    | '/api/public/hooks/sync-usage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/locations'
    | '/pricing'
    | '/refund-policy'
    | '/residential-proxy'
    | '/sitemap.xml'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/proxy'
    | '/app/settings'
    | '/app/admin/config'
    | '/app/admin/orders'
    | '/app/admin/seo'
    | '/app/admin/subusers'
    | '/app/admin/users'
    | '/app/admin/'
    | '/api/public/hooks/sync-usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LocationsRoute: typeof LocationsRoute
  PricingRoute: typeof PricingRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResidentialProxyRoute: typeof ResidentialProxyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksSyncUsageRoute: typeof ApiPublicHooksSyncUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential-proxy': {
      id: '/residential-proxy'
      path: '/residential-proxy'
      fullPath: '/residential-proxy'
      preLoaderRoute: typeof ResidentialProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proxy': {
      id: '/app/proxy'
      path: '/proxy'
      fullPath: '/app/proxy'
      preLoaderRoute: typeof AppProxyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/subusers': {
      id: '/app/admin/subusers'
      path: '/admin/subusers'
      fullPath: '/app/admin/subusers'
      preLoaderRoute: typeof AppAdminSubusersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/seo': {
      id: '/app/admin/seo'
      path: '/admin/seo'
      fullPath: '/app/admin/seo'
      preLoaderRoute: typeof AppAdminSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/orders': {
      id: '/app/admin/orders'
      path: '/admin/orders'
      fullPath: '/app/admin/orders'
      preLoaderRoute: typeof AppAdminOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/config': {
      id: '/app/admin/config'
      path: '/admin/config'
      fullPath: '/app/admin/config'
      preLoaderRoute: typeof AppAdminConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/sync-usage': {
      id: '/api/public/hooks/sync-usage'
      path: '/api/public/hooks/sync-usage'
      fullPath: '/api/public/hooks/sync-usage'
      preLoaderRoute: typeof ApiPublicHooksSyncUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProxyRoute: typeof AppProxyRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminConfigRoute: typeof AppAdminConfigRoute
  AppAdminOrdersRoute: typeof AppAdminOrdersRoute
  AppAdminSeoRoute: typeof AppAdminSeoRoute
  AppAdminSubusersRoute: typeof AppAdminSubusersRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProxyRoute: AppProxyRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminConfigRoute: AppAdminConfigRoute,
  AppAdminOrdersRoute: AppAdminOrdersRoute,
  AppAdminSeoRoute: AppAdminSeoRoute,
  AppAdminSubusersRoute: AppAdminSubusersRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LocationsRoute: LocationsRoute,
  PricingRoute: PricingRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResidentialProxyRoute: ResidentialProxyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksSyncUsageRoute: ApiPublicHooksSyncUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
